public class Calculator {
    public static Decimal add(Decimal num1, Decimal num2) {
        Decimal sum = num1 + num2;
        return sum;
    }
    public static Decimal sub(Decimal num1, Decimal num2) {
        Decimal sb = num1 - num2;
        return sb;
    }
    public static Decimal mul(Decimal num1, Decimal num2) {
        Decimal m = num1 * num2;
        return m;
        
    }
    public static Decimal div(Decimal num1, Decimal num2) {
        Decimal dv = num1 / num2;
        return dv;
    }
}